# Cloud
all:
  vars:
    OS: "xUbuntu_22.04"
    VERSION: "1.28"
    ansible_ssh_user: ubuntu
  children:
    kubernetes:
      children:
        control_plane:
          hosts:
            54.226.236.193:
        nodes:
          hosts:
            54.224.180.68:
