# Raspberry
all:
  vars:
    OS: "xUbuntu_22.04"
    VERSION: "1.28"
    ansible_ssh_user: kluster
  children:
    kubernetes:
      children:
        control_plane:
          hosts:
            192.168.2.120:
        nodes:
          hosts:
            192.168.2.121:
            192.168.2.122:
            192.168.2.123: