- name: Iniciando cluster Kubernetes
  shell: kubeadm init --pod-network-cidr=10.32.0.0/12 
                      --cri-socket=unix:///var/run/containerd/containerd.sock
                      --apiserver-cert-extra-sans=localhost
                      --apiserver-cert-extra-sans={{ hostvars.IPS_CONTROL_PLANE.IP_INTERNO[0] }}
                      --apiserver-cert-extra-sans={{ hostvars.IPS_CONTROL_PLANE.IP_EXTERNO[0] }}
                      
  args:
    chdir: $HOME
    creates: cluster_init.log

- name: Criando diretório .kube
  file: 
    path: /home/ubuntu/.kube
    state: directory
    owner: 1000
    group: 1000
    mode: 0775

- name: Copiando .kube/config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/ubuntu/.kube/config
    remote_src: yes
    owner: 1000
    group: 1000
    mode: 0660

- name: Importa .kube/config para máquina local
  fetch:
    src: /home/ubuntu/.kube/config
    dest: ./config


- name: Copiando join token
  shell: kubeadm token create --print-join-command
  register: join_command_raw

- name: Set join command as fact
  set_fact: join_command="{{ join_command_raw.stdout }}"

- name: Criando um dummy host com o comando para o join
  add_host:
    name: "COMANDO"
    join: "{{  join_command  }}"